### ISSUE TITLE
v91.0 problems with uploading

### ISSUE THREAD

**Issue by stanzabird** [maltejur/librewolf-choco#1]
* I first uploaded v91.0 with a .zip file instead of the -setup.exe which broke validation on Chocolatey.
* Second I rejected this version and tried to run the upload action again but it just doesnt start the action for some reason, that I can't see :/

** Version number: 91.0.0.1
** File URL: https://gitlab.com/librewolf-community/browser/windows/uploads/eb5467441f0af768ffb52beaf797a5e6/librewolf-91.0.en-US.win64-setup.exe

**Comment by stanzabird** [comment]
I can put in the above values, but the workflow doesn't start somehow..

**Comment by stanzabird** [comment]
The next day I was able to push a new v91.0.0.1 with the Publish workflow. yay :)

**Comment by maltejur** [comment]
Ah yes I only saw it now. Seems like you can't submit the same version twice, even if it fails.
