### ISSUE TITLE
Publishing release v94.0.2 gave me a weird error that doesn't seem to be 'user error' 

### ISSUE THREAD

**Issue by stanzabird** [maltejur/librewolf-choco#2]
* job id:  https://github.com/maltejur/librewolf-choco/actions/runs/1480613726

my input was:

* version: 94.0.2
* file_url: http://gitlab.com/librewolf-community/browser/windows/uploads/de3b3f6392576b5345ad3ae45b9e00cb/librewolf-94.0.2.en-US.win64-setup.exe

thanks in advance :)

**Comment by maltejur** [comment]
Hmm weird. I have tried to re-run the job and that succeeded, so maybe something was broken on chocolateys side.

**Comment by stanzabird** [comment]
I had to release a bug-fix version 94.0.2-2, it failed at first try and succeeded when re-run. I guess I can live with that :)

**Comment by maltejur** [comment]
From the logs it really looks like this is an error with choco
```
C:\ProgramData\Chocolatey\bin\choco.exe push librewolf.94.0.2.2.nupkg --source https://push.chocolatey.org/ -k *** --allow-unofficial
Chocolatey v0.11.3
Attempting to push librewolf.94.0.2.2.nupkg to https://push.chocolatey.org/
An error has occurred. It's possible the package version already exists on the repository.
Error: The process 'C:\ProgramData\Chocolatey\bin\choco.exe' failed with exit code 1
```
but if it works on the second try, it works. I still hope that with the next version this problem is gone again.

Oh and also, when creating the `94.0.2.2` on winget, you added a `v` to the front of the version, which is different from the versions before and also slightly broke things.
![image](https://user-images.githubusercontent.com/48161361/142650479-998777bc-c480-417f-aa3e-496c49a3a936.png)

**Comment by maltejur** [comment]
@stanzabird I think this error could be because of https://gitlab.com/librewolf-community/browser/windows/-/issues/114

**Comment by stanzabird** [comment]
Version v94.0.2-3 has been released on gitlab itself, winget and choco. I hope all workflows like this version ^.^

**Comment by maltejur** [comment]
Looks like everything worked and both workflows succeeded, but you shouldn't add the `v` to the front of `94.0.2.2` when entering the version number in the winget repo. This kind of breaks the pull request and I had to fix it manually.

**Comment by stanzabird** [comment]
Sorry, I knew that and still made the mistake. oops :/
